

services:
  # Database
  mongodb:
    image: mongo:latest
    container_name: agri-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - agri-network

  # Backend
  backend:
    build:
      context: ../backend
      dockerfile: ../devops/docker/backend/Dockerfile
    container_name: agri-backend
    restart: always
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/agri_db?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - agri-network

  # Frontend
  frontend:
    build:
      context: ../Frontend
      dockerfile: ../devops/docker/frontend/Dockerfile
    container_name: agri-frontend
    restart: always
    networks:
      - agri-network

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./docker/nginx
    container_name: agri-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - agri-network

  # Jenkins
  jenkins:
    build:
      context: ./docker/jenkins
    container_name: agri-jenkins
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agri-network

networks:
  agri-network:
    driver: bridge

volumes:
  mongo-data:
  jenkins-data:

