/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandRecordsRouteImport } from './routes/land-records'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropMonitoringRouteImport } from './routes/crop-monitoring'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AerialRouteImport } from './routes/aerial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRecordsRoute = LandRecordsRouteImport.update({
  id: '/land-records',
  path: '/land-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropMonitoringRoute = CropMonitoringRouteImport.update({
  id: '/crop-monitoring',
  path: '/crop-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AerialRoute = AerialRouteImport.update({
  id: '/aerial',
  path: '/aerial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aerial': typeof AerialRoute
  '/analytics': typeof AnalyticsRoute
  '/crop-monitoring': typeof CropMonitoringRoute
  '/dashboard': typeof DashboardRoute
  '/farmers': typeof FarmersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/land-records': typeof LandRecordsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aerial': typeof AerialRoute
  '/analytics': typeof AnalyticsRoute
  '/crop-monitoring': typeof CropMonitoringRoute
  '/dashboard': typeof DashboardRoute
  '/farmers': typeof FarmersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/land-records': typeof LandRecordsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aerial': typeof AerialRoute
  '/analytics': typeof AnalyticsRoute
  '/crop-monitoring': typeof CropMonitoringRoute
  '/dashboard': typeof DashboardRoute
  '/farmers': typeof FarmersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/land-records': typeof LandRecordsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aerial'
    | '/analytics'
    | '/crop-monitoring'
    | '/dashboard'
    | '/farmers'
    | '/forgot-password'
    | '/land-records'
    | '/login'
    | '/notifications'
    | '/register'
    | '/schemes'
    | '/settings'
    | '/users'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aerial'
    | '/analytics'
    | '/crop-monitoring'
    | '/dashboard'
    | '/farmers'
    | '/forgot-password'
    | '/land-records'
    | '/login'
    | '/notifications'
    | '/register'
    | '/schemes'
    | '/settings'
    | '/users'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/aerial'
    | '/analytics'
    | '/crop-monitoring'
    | '/dashboard'
    | '/farmers'
    | '/forgot-password'
    | '/land-records'
    | '/login'
    | '/notifications'
    | '/register'
    | '/schemes'
    | '/settings'
    | '/users'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AerialRoute: typeof AerialRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CropMonitoringRoute: typeof CropMonitoringRoute
  DashboardRoute: typeof DashboardRoute
  FarmersRoute: typeof FarmersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandRecordsRoute: typeof LandRecordsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  SchemesRoute: typeof SchemesRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land-records': {
      id: '/land-records'
      path: '/land-records'
      fullPath: '/land-records'
      preLoaderRoute: typeof LandRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-monitoring': {
      id: '/crop-monitoring'
      path: '/crop-monitoring'
      fullPath: '/crop-monitoring'
      preLoaderRoute: typeof CropMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aerial': {
      id: '/aerial'
      path: '/aerial'
      fullPath: '/aerial'
      preLoaderRoute: typeof AerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AerialRoute: AerialRoute,
  AnalyticsRoute: AnalyticsRoute,
  CropMonitoringRoute: CropMonitoringRoute,
  DashboardRoute: DashboardRoute,
  FarmersRoute: FarmersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandRecordsRoute: LandRecordsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  SchemesRoute: SchemesRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
